In [1]:
import numpy as np

ventas_mensuales = np.array([
    [10000, 15000, 33000, 20000],
    [11000, 15500, 36000, 25000],
    [12000, 16000, 39000, 30000],
    [13000, 16500, 42000, 35000],
    [14000, 17000, 45000, 40000],
    [15000, 17500, 48000, 45000],
    [16000, 18000, 51000, 50000],
    [17000, 18500, 54000, 55000],
    [18000, 19000, 57000, 60000],
    [19000, 19500, 60000, 65000],
    [20000, 20000, 63000, 70000],
    [21000, 20500, 66000, 75000]
])

print("Ventas mensuales:")
print(ventas_mensuales)

total_de_ventas_producto = np.sum(ventas_mensuales, axis=0)

print("Total de Ventas por Producto:")
print(total_de_ventas_producto)


Ventas mensuales:
[[10000 15000 33000 20000]
 [11000 15500 36000 25000]
 [12000 16000 39000 30000]
 [13000 16500 42000 35000]
 [14000 17000 45000 40000]
 [15000 17500 48000 45000]
 [16000 18000 51000 50000]
 [17000 18500 54000 55000]
 [18000 19000 57000 60000]
 [19000 19500 60000 65000]
 [20000 20000 63000 70000]
 [21000 20500 66000 75000]]
Total de Ventas por Producto:
[186000 213000 594000 570000]
